[package]
name = "fnp_content"
description = "Fiends n Patrons gameplay plugins: weapons, patrons, items and enemies."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
